# Generated by Django 5.2.7 on 2025-12-14 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profile_bmi_alter_profile_calculation_method_and_more'),
        ('recipes', '0003_rename_carbohydrates_recipe_carbohydrate'),
        ('recommendations', '0002_plan_delete_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source', models.CharField(choices=[('ai_generated', 'Ai Generated'), ('user_selected', 'User Selected')], default='ai_generated', max_length=20)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='profiles.profile')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'db_table': 'Meals',
                'unique_together': {('profile', 'date', 'meal_type')},
            },
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
