# Generated by Django 5.2.7 on 2025-11-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender'), ('NB', 'Non-binary'), ('AG', 'Agender'), ('GF', 'Genderfluid'), ('BI', 'Bigender'), ('PAN', 'Pangender'), ('GQ', 'Genderqueer'), ('DB', 'Demiboy'), ('DG', 'Demigirl'), ('AN', 'Androgyne'), ('NE', 'Neutrois'), ('TRI', 'Trigender'), ('GX', 'Genderflux'), ('XE', 'Xenogender'), ('2S', 'Two-Spirit'), ('AL', 'Aliagender'), ('GG', 'Graygender'), ('PO', 'Polygender'), ('O', 'Inna')], max_length=3, null=True),
        ),
    ]
