# Generated by Django 5.2.7 on 2025-11-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nutritional_goal',
            field=models.CharField(blank=True, choices=[('LOSE', 'Lose Weight'), ('MAINTAIN', 'Maintain Weight'), ('GAIN', 'Gain Weight')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='physical_activity',
            field=models.CharField(blank=True, choices=[('SEDENTARY', 'Sedentary (little or no exercise)'), ('LIGHT', 'Lightly active (light exercise/sports 1-3 days/week)'), ('MODERATE', 'Moderately active (moderate exercise/sports 3-5 days/week)'), ('VERY', 'Very active (hard exercise/sports 6-7 days a week)'), ('EXTRA', 'Extra active (very hard exercise/sports & physical job)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender'), ('NB', 'Non-binary'), ('AG', 'Agender'), ('GF', 'Genderfluid'), ('BI', 'Bigender'), ('PAN', 'Pangender'), ('GQ', 'Genderqueer'), ('DB', 'Demiboy'), ('DG', 'Demigirl'), ('AN', 'Androgyne'), ('NE', 'Neutrois'), ('TRI', 'Trigender'), ('GX', 'Genderflux'), ('XE', 'Xenogender'), ('2S', 'Two-Spirit'), ('AL', 'Aliagender'), ('GG', 'Graygender'), ('PO', 'Polygender'), ('HB', 'Helboj'), ('O', 'Inna')], max_length=3, null=True),
        ),
    ]
