# Generated by Django 5.2.7 on 2025-11-13 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_nutritional_goal_profile_physical_activity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='profile',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Body Mass Index', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='calculation_method',
            field=models.CharField(choices=[('MIFFLIN', 'Mifflin-St Jeor'), ('HARRIS_BENEDICT', 'Harris-Benedict')], default='MIFFLIN', help_text='Method used for calculating daily calorie needs', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='calculations_last_updated',
            field=models.DateTimeField(blank=True, help_text='Last time nutritional calculations were performed', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='calorie_adjustment',
            field=models.IntegerField(default=0, help_text='Manual calorie adjustment (-1000 to +1000 kcal)', validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='cpm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Daily Energy Expenditure (CPM)', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_calories',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Recommended daily calories (with goal adjustment)', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_carbohydrates',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Recommended daily carbohydrates in grams', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_fat',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Recommended daily fat in grams', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_protein',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Recommended daily protein in grams', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth for age calculation', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ppm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Basal Metabolic Rate (PPM)', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender'), ('NB', 'Non-binary'), ('AG', 'Agender'), ('GF', 'Genderfluid'), ('BI', 'Bigender'), ('PAN', 'Pangender'), ('GQ', 'Genderqueer'), ('DB', 'Demiboy'), ('DG', 'Demigirl'), ('AN', 'Androgyne'), ('NE', 'Neutrois'), ('TRI', 'Trigender'), ('GX', 'Genderflux'), ('XE', 'Xenogender'), ('2S', 'Two-Spirit'), ('AL', 'Aliagender'), ('GG', 'Graygender'), ('PO', 'Polygender'), ('HB', 'Helboj'), ('O', 'Other')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters (50-300 cm)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='physical_activity',
            field=models.CharField(blank=True, choices=[('SEDENTARY', 'Lying down, no movement (PAL: 1.2)'), ('LOW', 'Low activity (office work, little movement) (PAL: 1.4-1.5)'), ('MODERATE', 'Moderate activity (light work + recreational movement) (PAL: 1.6-1.7)'), ('HIGH', 'High activity (physical work, regular sport) (PAL: 1.8-2.0)'), ('VERY_HIGH', 'Very high activity (athlete, heavy work) (PAL: 2.1-2.4)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms (20-500 kg)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
