# Generated by Django 5.2.7 on 2025-11-14 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_options_profile_bmi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='daily_carbohydrates',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='daily_fat',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='daily_protein',
        ),
        migrations.AddField(
            model_name='profile',
            name='carb_percentage',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Percentage of calories from carbohydrates', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fat_percentage',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Percentage of calories from fat', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='protein_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Protein intake per kg of body weight', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='protein_percentage',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Percentage of calories from protein', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='calorie_adjustment',
            field=models.IntegerField(blank=True, default=None, help_text='Manual calorie adjustment (-1000 to +1000 kcal)', null=True, validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
