# Generated by Django 5.2.7 on 2025-11-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profile_daily_carbohydrates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_carbohydrates',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Recommended daily carbohydrates in grams', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_fat',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Recommended daily fat in grams', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_protein',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Recommended daily protein in grams', max_digits=6, null=True),
        ),
    ]
