# Generated by Django 5.2.7 on 2025-11-14 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_daily_carbohydrates_profile_daily_fat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_carb_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom carbohydrate percentage (0.0 to 1.0). Leave empty for automatic calculation.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.8)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='custom_fat_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom fat percentage (0.0 to 1.0). Leave empty for automatic calculation.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.7)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='custom_protein_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom protein percentage (0.0 to 1.0). Leave empty for automatic calculation.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.7)]),
        ),
    ]
