# Generated by Django 5.2.7 on 2025-11-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sugar',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
