# Generated by Django 5.2.7 on 2025-11-13 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_ingredients_recipe_sugar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='carbohydrates',
            new_name='carbohydrate',
        ),
    ]
