# Generated by Django 5.2.7 on 2026-05-09 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_carbohydrates_recipe_carbohydrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(max_length=255, unique=True)),
                ('fdc_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('fdc_description', models.CharField(blank=True, max_length=500, null=True)),
                ('fdc_category', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdc_nutrient_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Nutrients',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.CharField(max_length=500)),
                ('quantity_in_grams', models.FloatField(blank=True, null=True)),
                ('preparation', models.CharField(blank=True, max_length=200, null=True)),
                ('parse_confidence', models.FloatField(blank=True, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_uses', to='recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_ingredients', to='recipes.recipe')),
            ],
            options={
                'db_table': 'Recipe_Ingredients',
            },
        ),
        migrations.CreateModel(
            name='IngredientNutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_per_100g', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_values', to='recipes.ingredient')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.nutrient')),
            ],
            options={
                'db_table': 'Ingredient_Nutrients',
                'unique_together': {('ingredient', 'nutrient')},
            },
        ),
    ]
