# Generated by Django 5.2.7 on 2026-05-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_ingredient_nutrient_recipeingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrient',
            name='fdc_nutrient_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
