# Generated by Django 5.2.7 on 2026-05-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_nutrient_fdc_nutrient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='aggregated_nutrients',
            field=models.JSONField(default=list),
        ),
    ]
